# Generated by Django 4.2 on 2024-11-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_constitution_id_alter_news_id_alter_video_id'),
    ]

    operations = [
    ]
